import { MenuItem } from '../types'

export const menuItems: MenuItem[] = [
  // === COFFEE ===
  {
    id: 'caramel-latte',
    name: 'Caramel Latte',
    description: 'Espresso lembut dengan sirup karamel premium dan steamed milk yang creamy, menciptakan harmoni manis sempurna.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80',
    prices: { S: 32000, M: 38000, L: 44000 },
    rating: 4.8, reviewCount: 342, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Sweet'], pairsWith: ['croffle', 'cheesecake'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 250 },
      { inventoryItemId: 'inv-003', amount: 20 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'spanish-latte',
    name: 'Spanish Latte',
    description: 'Double espresso dengan susu kental manis dan fresh milk — kaya, bold, dan penuh karakter.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80',
    prices: { S: 35000, M: 42000, L: 48000 },
    rating: 4.9, reviewCount: 489, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Bold'], pairsWith: ['croissant-sandwich', 'truffle-fries'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 200 },
      { inventoryItemId: 'inv-019', amount: 30 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'americano',
    name: 'Americano',
    description: 'Espresso single origin dengan hot water yang presisi — clean, bold, dan pure kopi.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80',
    prices: { S: 22000, M: 28000, L: 34000 },
    rating: 4.6, reviewCount: 201, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Black Coffee', 'Pure'], pairsWith: ['croissant-sandwich'], preparationTime: 4,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso klasik dengan steamed milk dan milk foam tebal — klasik yang tidak pernah salah.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&q=80',
    prices: { S: 26000, M: 32000, L: 38000 },
    rating: 4.7, reviewCount: 178, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Classic'], pairsWith: ['cheesecake', 'croffle'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 150 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'matcha-latte',
    name: 'Matcha Latte',
    description: 'Matcha ceremonial grade premium dari Jepang dengan oat milk — earthy, smooth, dan menenangkan.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80',
    prices: { S: 33000, M: 40000, L: 46000 },
    rating: 4.8, reviewCount: 267, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Matcha'], pairsWith: ['cheesecake', 'croffle'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-004', amount: 15 },
      { inventoryItemId: 'inv-010', amount: 250 },
      { inventoryItemId: 'inv-006', amount: 10 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'vanilla-latte',
    name: 'Vanilla Latte',
    description: 'Espresso dengan vanilla bean syrup dan steamed milk — lembut, sweet, dan sangat comforting.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
    prices: { S: 31000, M: 38000, L: 44000 },
    rating: 4.7, reviewCount: 156, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Sweet', 'Smooth'], pairsWith: ['croffle', 'tiramisu'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 250 },
      { inventoryItemId: 'inv-009', amount: 20 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'hazelnut-latte',
    name: 'Hazelnut Latte',
    description: 'Espresso dengan hazelnut syrup premium dan steamed milk — nutty, warm, dan sangat cozy.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=600&q=80',
    prices: { S: 31000, M: 38000, L: 44000 },
    rating: 4.6, reviewCount: 134, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Nutty', 'Warm'], pairsWith: ['croissant-sandwich'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 250 },
      { inventoryItemId: 'inv-013', amount: 20 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'cafe-mocha',
    name: 'Cafe Mocha',
    description: 'Espresso dengan dark chocolate sauce dan steamed milk — intensitas kopi bertemu richness coklat.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=600&q=80',
    prices: { S: 33000, M: 40000, L: 46000 },
    rating: 4.7, reviewCount: 198, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Chocolate', 'Rich'], pairsWith: ['chocolate-lava', 'cheesecake'], preparationTime: 6,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 200 },
      { inventoryItemId: 'inv-005', amount: 25 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'butterscotch-latte',
    name: 'Butterscotch Latte',
    description: 'Espresso dengan butterscotch sauce artisan dan milk foam — signature Rehan yang wajib dicoba.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?w=600&q=80',
    prices: { S: 34000, M: 40000, L: 47000 },
    rating: 4.9, reviewCount: 312, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Signature', 'Bestseller'], pairsWith: ['croffle', 'cheesecake'], preparationTime: 6,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 250 },
      { inventoryItemId: 'inv-003', amount: 20 },
      { inventoryItemId: 'inv-006', amount: 5 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'affogato',
    name: 'Affogato',
    description: 'Double espresso dituangkan di atas vanilla ice cream premium — hot meets cold dalam satu sajian.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&q=80',
    prices: { S: 40000, M: 45000, L: 52000 },
    rating: 4.8, reviewCount: 223, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Dessert Coffee', 'Unique'], pairsWith: ['chocolate-lava'], preparationTime: 4,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 25 },
      { inventoryItemId: 'inv-002', amount: 100 },
      { inventoryItemId: 'inv-009', amount: 10 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'v60-manual-brew',
    name: 'V60 Manual Brew',
    description: 'Single origin pour-over dengan V60 dripper — bright, clean, dan nuansa floral yang kompleks.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600&q=80',
    prices: { S: 30000, M: 35000, L: 42000 },
    rating: 4.7, reviewCount: 89, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Manual Brew', 'Specialty'], pairsWith: ['croissant-sandwich'], preparationTime: 8,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 20 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'cold-brew',
    name: 'Cold Brew',
    description: 'Kopi cold brew 12 jam dengan profil rasa smooth, less acidic, dan full body yang satisfying.',
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80',
    prices: { S: 32000, M: 38000, L: 44000 },
    rating: 4.6, reviewCount: 145, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Cold', 'Smooth'], pairsWith: ['truffle-fries'], preparationTime: 2,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 22 },
      { inventoryItemId: 'inv-008', amount: 1 },
      { inventoryItemId: 'inv-011', amount: 1 },
    ],
  },

  // === NON-COFFEE ===
  {
    id: 'chocolate-signature',
    name: 'Chocolate Signature',
    description: 'Dark chocolate premium 70% cacao dengan steamed milk dan whipped cream — indulgent dan rich.',
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&q=80',
    prices: { S: 32000, M: 38000, L: 44000 },
    rating: 4.8, reviewCount: 234, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Chocolate', 'No Coffee'], pairsWith: ['croffle', 'chocolate-lava'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-005', amount: 30 },
      { inventoryItemId: 'inv-002', amount: 200 },
      { inventoryItemId: 'inv-006', amount: 10 },
      { inventoryItemId: 'inv-020', amount: 30 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'lychee-tea',
    name: 'Lychee Tea',
    description: 'Teh hijau premium dengan sirup lychee segar dan popping boba — refreshing dan fruity.',
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
    prices: { S: 27000, M: 32000, L: 38000 },
    rating: 4.6, reviewCount: 167, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Tea', 'Fruity', 'No Coffee'], pairsWith: ['truffle-fries', 'chicken-katsu'], preparationTime: 4,
    ingredients: [
      { inventoryItemId: 'inv-014', amount: 5 },
      { inventoryItemId: 'inv-003', amount: 20 },
      { inventoryItemId: 'inv-006', amount: 10 },
      { inventoryItemId: 'inv-008', amount: 1 },
      { inventoryItemId: 'inv-011', amount: 1 },
    ],
  },
  {
    id: 'peach-tea',
    name: 'Peach Tea',
    description: 'Earl grey tea dengan peach syrup dan slice peach segar — floral, sweet, dan sangat Instagramable.',
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    prices: { S: 27000, M: 32000, L: 38000 },
    rating: 4.5, reviewCount: 143, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Tea', 'Fruity', 'No Coffee'], pairsWith: ['cheesecake'], preparationTime: 4,
    ingredients: [
      { inventoryItemId: 'inv-014', amount: 5 },
      { inventoryItemId: 'inv-009', amount: 20 },
      { inventoryItemId: 'inv-006', amount: 10 },
      { inventoryItemId: 'inv-008', amount: 1 },
      { inventoryItemId: 'inv-011', amount: 1 },
    ],
  },
  {
    id: 'mojito-lychee',
    name: 'Mojito Lychee',
    description: 'Mojito segar dengan lychee dan mint — non-alcoholic, refreshing, dan sempurna untuk siang hari.',
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&q=80',
    prices: { S: 30000, M: 35000, L: 42000 },
    rating: 4.7, reviewCount: 189, isAvailable: true, isBestseller: false, isNew: true, isPromo: false,
    tags: ['New', 'Refreshing', 'No Coffee'], pairsWith: ['truffle-fries', 'chicken-katsu'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-014', amount: 5 },
      { inventoryItemId: 'inv-003', amount: 20 },
      { inventoryItemId: 'inv-006', amount: 15 },
      { inventoryItemId: 'inv-008', amount: 1 },
      { inventoryItemId: 'inv-011', amount: 1 },
    ],
  },
  {
    id: 'strawberry-milk',
    name: 'Strawberry Milk',
    description: 'Fresh strawberry blended dengan susu premium dan strawberry compote — sweet, creamy, dan aesthetic.',
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80',
    prices: { S: 30000, M: 35000, L: 42000 },
    rating: 4.6, reviewCount: 121, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Fruity', 'No Coffee'], pairsWith: ['cheesecake', 'croffle'], preparationTime: 5,
    ingredients: [
      { inventoryItemId: 'inv-002', amount: 250 },
      { inventoryItemId: 'inv-006', amount: 15 },
      { inventoryItemId: 'inv-008', amount: 1 },
      { inventoryItemId: 'inv-011', amount: 1 },
    ],
  },

  // === FOOD ===
  {
    id: 'chicken-katsu',
    name: 'Chicken Katsu',
    description: 'Ayam fillet premium breaded dengan panko, digoreng crispy dan disajikan dengan katsu sauce dan salad segar.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=600&q=80',
    prices: { S: 48000, M: 55000, L: 62000 },
    rating: 4.7, reviewCount: 298, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Chicken'], pairsWith: ['lychee-tea', 'americano'], preparationTime: 15,
    ingredients: [
      { inventoryItemId: 'inv-012', amount: 150 },
      { inventoryItemId: 'inv-018', amount: 30 },
      { inventoryItemId: 'inv-006', amount: 5 },
    ],
  },
  {
    id: 'creamy-pasta',
    name: 'Creamy Pasta',
    description: 'Fettuccine dengan creamy alfredo sauce premium, mushroom sauteed, dan parmesan freshly grated.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    prices: { S: 50000, M: 58000, L: 65000 },
    rating: 4.6, reviewCount: 187, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Pasta', 'Creamy'], pairsWith: ['americano', 'cappuccino'], preparationTime: 18,
    ingredients: [
      { inventoryItemId: 'inv-015', amount: 150 },
      { inventoryItemId: 'inv-002', amount: 150 },
      { inventoryItemId: 'inv-006', amount: 5 },
    ],
  },
  {
    id: 'spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    description: 'Spaghetti dengan slow-cooked beef bolognese sauce selama 3 jam — rich, hearty, dan memuaskan.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80',
    prices: { S: 50000, M: 58000, L: 65000 },
    rating: 4.5, reviewCount: 156, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Pasta', 'Beef'], pairsWith: ['americano'], preparationTime: 15,
    ingredients: [
      { inventoryItemId: 'inv-015', amount: 150 },
      { inventoryItemId: 'inv-016', amount: 120 },
      { inventoryItemId: 'inv-006', amount: 5 },
    ],
  },
  {
    id: 'truffle-fries',
    name: 'Truffle Fries',
    description: 'Kentang goreng crispy dengan truffle oil premium, parmesan, dan rosemary — cafe snack yang addictive.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&q=80',
    prices: { S: 38000, M: 45000, L: 52000 },
    rating: 4.8, reviewCount: 356, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Snack', 'Truffle'], pairsWith: ['caramel-latte', 'spanish-latte'], preparationTime: 10,
    ingredients: [
      { inventoryItemId: 'inv-017', amount: 200 },
      { inventoryItemId: 'inv-006', amount: 5 },
    ],
  },
  {
    id: 'croissant-sandwich',
    name: 'Croissant Sandwich',
    description: 'Croissant butter premium dengan chicken ham, egg, cheese, dan saus thousand island — breakfast favorite.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600&q=80',
    prices: { S: 45000, M: 52000, L: 59000 },
    rating: 4.7, reviewCount: 223, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Sandwich', 'Breakfast'], pairsWith: ['americano', 'vanilla-latte'], preparationTime: 10,
    ingredients: [
      { inventoryItemId: 'inv-012', amount: 80 },
      { inventoryItemId: 'inv-002', amount: 50 },
      { inventoryItemId: 'inv-006', amount: 5 },
    ],
  },
  {
    id: 'beef-blackpepper-rice',
    name: 'Beef Blackpepper Rice',
    description: 'Beef slice premium dengan black pepper sauce rich, disajikan dengan steamed rice dan acar.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80',
    prices: { S: 58000, M: 65000, L: 72000 },
    rating: 4.6, reviewCount: 167, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Beef', 'Rice', 'Spicy'], pairsWith: ['lychee-tea', 'peach-tea'], preparationTime: 20,
    ingredients: [
      { inventoryItemId: 'inv-016', amount: 150 },
      { inventoryItemId: 'inv-006', amount: 10 },
    ],
  },
  {
    id: 'chicken-salted-egg',
    name: 'Chicken Salted Egg',
    description: 'Ayam crispy dengan salted egg sauce creamy yang rich — comfort food premium yang viral di mana-mana.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1626509653291-18d9a934b9db?w=600&q=80',
    prices: { S: 55000, M: 62000, L: 70000 },
    rating: 4.8, reviewCount: 278, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Chicken', 'Viral'], pairsWith: ['peach-tea', 'lychee-tea'], preparationTime: 18,
    ingredients: [
      { inventoryItemId: 'inv-012', amount: 150 },
      { inventoryItemId: 'inv-018', amount: 25 },
      { inventoryItemId: 'inv-002', amount: 80 },
    ],
  },
  {
    id: 'salmon-rice-bowl',
    name: 'Salmon Rice Bowl',
    description: 'Salmon teriyaki glazed dengan steamed rice, edamame, dan sesame dressing — healthy dan premium.',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',
    prices: { S: 65000, M: 72000, L: 82000 },
    rating: 4.7, reviewCount: 134, isAvailable: true, isBestseller: false, isNew: true, isPromo: false,
    tags: ['New', 'Salmon', 'Healthy'], pairsWith: ['peach-tea', 'matcha-latte'], preparationTime: 15,
    ingredients: [
      { inventoryItemId: 'inv-006', amount: 10 },
    ],
  },

  // === DESSERT ===
  {
    id: 'cheesecake',
    name: 'Cheesecake',
    description: 'New York style cheesecake dengan cream cheese premium dan graham cracker crust — thick, creamy, dan irresistible.',
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=80',
    prices: { S: 36000, M: 42000, L: 50000 },
    rating: 4.8, reviewCount: 312, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Cake'], pairsWith: ['caramel-latte', 'matcha-latte'], preparationTime: 3,
    ingredients: [
      { inventoryItemId: 'inv-002', amount: 100 },
      { inventoryItemId: 'inv-006', amount: 30 },
    ],
  },
  {
    id: 'croffle',
    name: 'Croffle',
    description: 'Croissant dough dimasak dengan waffle iron — crispy di luar, flaky di dalam, disajikan dengan maple syrup.',
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600&q=80',
    prices: { S: 32000, M: 38000, L: 45000 },
    rating: 4.9, reviewCount: 423, isAvailable: true, isBestseller: true, isNew: false, isPromo: false,
    tags: ['Bestseller', 'Signature', 'Viral'], pairsWith: ['caramel-latte', 'butterscotch-latte'], preparationTime: 8,
    ingredients: [
      { inventoryItemId: 'inv-002', amount: 50 },
      { inventoryItemId: 'inv-006', amount: 15 },
    ],
  },
  {
    id: 'tiramisu',
    name: 'Tiramisu',
    description: 'Classic Italian tiramisu dengan ladyfinger, mascarpone, espresso shot, dan cocoa powder — decadent dan authentic.',
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    prices: { S: 38000, M: 45000, L: 52000 },
    rating: 4.7, reviewCount: 189, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Italian', 'Classic'], pairsWith: ['americano', 'cappuccino'], preparationTime: 3,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-005', amount: 20 },
      { inventoryItemId: 'inv-006', amount: 20 },
    ],
  },
  {
    id: 'chocolate-lava',
    name: 'Chocolate Lava',
    description: 'Warm chocolate molten cake dengan lava center yang meleleh, disajikan dengan vanilla ice cream — absolute indulgence.',
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80',
    prices: { S: 40000, M: 45000, L: 52000 },
    rating: 4.8, reviewCount: 245, isAvailable: true, isBestseller: false, isNew: false, isPromo: false,
    tags: ['Chocolate', 'Warm'], pairsWith: ['affogato', 'cafe-mocha'], preparationTime: 12,
    ingredients: [
      { inventoryItemId: 'inv-005', amount: 35 },
      { inventoryItemId: 'inv-006', amount: 20 },
      { inventoryItemId: 'inv-002', amount: 50 },
    ],
  },

  // === BUNDLE ===
  {
    id: 'coffee-croffle-bundle',
    name: 'Coffee & Croffle Package',
    description: 'Pilih 1 minuman latte favoritmu + 1 Croffle signature — hemat Rp 10.000 dari harga normal.',
    category: 'bundle',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
    prices: { S: 60000, M: 68000, L: 78000 },
    rating: 4.9, reviewCount: 567, isAvailable: true, isBestseller: true, isNew: false, isPromo: true,
    tags: ['Promo', 'Bundle', 'Best Value'], pairsWith: [], preparationTime: 10,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 18 },
      { inventoryItemId: 'inv-002', amount: 250 },
      { inventoryItemId: 'inv-006', amount: 20 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'dinner-couple-bundle',
    name: 'Dinner Couple Package',
    description: '2 Main Course + 2 Minuman pilihan — perfect dinner date di Rehan Cafe. Hemat Rp 25.000.',
    category: 'bundle',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    prices: { S: 155000, M: 175000, L: 195000 },
    rating: 4.8, reviewCount: 234, isAvailable: true, isBestseller: false, isNew: false, isPromo: true,
    tags: ['Promo', 'Bundle', 'Couple'], pairsWith: [], preparationTime: 20,
    ingredients: [
      { inventoryItemId: 'inv-012', amount: 300 },
      { inventoryItemId: 'inv-001', amount: 36 },
      { inventoryItemId: 'inv-002', amount: 400 },
      { inventoryItemId: 'inv-008', amount: 2 },
    ],
  },
  {
    id: 'study-pack-bundle',
    name: 'Study All Day Pack',
    description: '1 Manual Brew + 1 Croissant Sandwich — fuel untuk seharian kerja atau belajar. Hemat Rp 9.000.',
    category: 'bundle',
    image: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=600&q=80',
    prices: { S: 72000, M: 78000, L: 88000 },
    rating: 4.7, reviewCount: 189, isAvailable: true, isBestseller: false, isNew: false, isPromo: true,
    tags: ['Promo', 'Bundle', 'Workday'], pairsWith: [], preparationTime: 12,
    ingredients: [
      { inventoryItemId: 'inv-001', amount: 20 },
      { inventoryItemId: 'inv-012', amount: 80 },
      { inventoryItemId: 'inv-002', amount: 150 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
  {
    id: 'sweet-treat-bundle',
    name: 'Sweet Treat Bundle',
    description: '1 Cheesecake slice + 1 Matcha Latte — sweet pairing sempurna untuk me-time atau sore santai.',
    category: 'bundle',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
    prices: { S: 65000, M: 70000, L: 80000 },
    rating: 4.8, reviewCount: 156, isAvailable: true, isBestseller: false, isNew: false, isPromo: true,
    tags: ['Promo', 'Bundle', 'Sweet'], pairsWith: [], preparationTime: 8,
    ingredients: [
      { inventoryItemId: 'inv-004', amount: 15 },
      { inventoryItemId: 'inv-010', amount: 250 },
      { inventoryItemId: 'inv-006', amount: 40 },
      { inventoryItemId: 'inv-008', amount: 1 },
    ],
  },
]

export const getCategoryLabel = (category: string): string => {
  const labels: Record<string, string> = {
    coffee: 'Kopi',
    'non-coffee': 'Non-Kopi',
    food: 'Makanan',
    dessert: 'Dessert',
    bundle: 'Paket Bundle',
  }
  return labels[category] || category
}

export const getMenuById = (id: string): MenuItem | undefined =>
  menuItems.find((item) => item.id === id)

export const getMenuByCategory = (category: string): MenuItem[] =>
  category === 'all' ? menuItems : menuItems.filter((item) => item.category === category)
